spring:
  application:
    name: stock-alert

  # Spring Security 자동 설정 제외
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  # MySQL Database Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock_alert?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: stock_user
    password: stock_password

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true
    open-in-view: false

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-minimum-32-characters-for-hs256-algorithm-security}
  access-token-validity: 3600000  # 1시간 (밀리초)
  refresh-token-validity: 604800000  # 7일 (밀리초)

monitoring:
  stock:
    # 주식 가격 업데이트 주기 (초)
    update-interval: 60
    # 알림 체크 주기 (초)
    alert-check-interval: 30
    # 배치 처리 크기
    batch-size: 100

logging:
  level:
    root: INFO
    sotck.stockalert: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.connections.pooling: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %X{correlationId:-} %X{userId:-} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %X{correlationId:-} %X{userId:-} %-5level %logger{36} - %msg%n"