spring:
  application:
    name: stock-alert

  # MySQL Database Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock_alert?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: stock_user
    password: stock_password

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
    show-sql: true
    open-in-view: false

# Stock API Configuration
stock:
  api:
    # 한국투자증권 Open API 설정
    kis:
      base-url: https://openapi.koreainvestment.com:9443
      app-key: ${KIS_APP_KEY:your-app-key}
      app-secret: ${KIS_APP_SECRET:your-app-secret}

    # 기타 주식 API (확장 가능)
    # yahoo:
    #   base-url: https://query1.finance.yahoo.com
    # alpha-vantage:
    #   api-key: ${ALPHA_VANTAGE_KEY:your-api-key}

# Monitoring Configuration
monitoring:
  stock:
    # 주식 가격 업데이트 주기 (초)
    update-interval: 60
    # 알림 체크 주기 (초)
    alert-check-interval: 30
    # 배치 처리 크기
    batch-size: 100